packages:
  - ansible
  - xz
  - bat
  - coreutils
  - sqlite
  - wget
  - 1password-cli
  - burp-suite
  - parallels
  - scroll-reverser
  - vlc
  - zed
  - docker-desktop
  - google-drive
  - protonvpn
  - stats
  - bartender
  - ferdium
  - notchnook
  - raycast
  - visual-studio-code
  - yubico-authenticator
  - mise
  - firefox
  - font-hack-nerd-font
  - font-hackgen-nerd
  - gimp
  - google-drive
  - nmap
  - ldns
  - atok
  - mas
  - jetbrains-toolbox
mas_apps:
  - 937984704 # Amphetamine
  - 549083868 # Display Menu
  - 1346247457 # Endel
  - 1532419400 # MeetingBar
  - 497799835 # Xcode
