[[plugins]]
  repo = 'Shougo/dein.vim'

[[plugins]]
  repo = 'sheerun/vim-polyglot'

[[plugins]]
  repo = 'kaicataldo/material.vim'
  hook_add = '''
    let g:material_theme_style = 'ocean'
    colorscheme material
  '''

[[plugins]]
  repo = 'tpope/vim-surround'
  on_event = 'InsertEnter'

[[plugins]]
  repo = 'airblade/vim-gitgutter'

[[plugins]]
  repo = 'earthly/earthly.vim'

[[plugins]]
  repo = 'github/copilot.vim'
