- name: "install generic packages"
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ packages }}"
  when: ansible_os_family == 'Darwin'
- name: "install AppStore packages"
  community.general.mas:
    id: "{{ item }}"
    state: present
  with_items: "{{ mas_apps }}"
  when: ansible_os_family == 'Darwin'