- name: "install neovim for macOS"
  community.general.homebrew:
    name: neovim
    state: present
  when: ansible_os_family == 'Darwin'
- name: "install deps for macOS"
  community.general.homebrew:
    name: git
    state: latest
  when: ansible_os_family == 'Darwin'

- name: "install neovim for Ubuntu"
  ansible.builtin.apt:
    name: neovim
    state: present
  when: ansible_os_family == 'Debian'
- name: "install deps for Ubuntu"
  ansible.builtin.apt:
    name: git
    state: present
  when: ansible_os_family == 'Debian'

- name: "install neovim for Archlinux"
  community.general.pacman:
    name: neovim
    state: latest
  when: ansible_os_family == 'Archlinux'
- name: "install deno and deps for Archlinux"
  community.general.pacman:
    name: git
    state: latest
  when: ansible_os_family == 'Archlinux'

- name: "create cache folder"
  ansible.builtin.file:
    path: "{{ home_dir }}/.cache/nvim"
    state: directory
    recurse: yes
    mode: "0755"
- name: "install lazy.nvim"
  ansible.builtin.git:
    repo: "https://github.com/folke/lazy.nvim.git"
    dest: "{{ home_dir }}/.cache/nvim/lazy.nvim"
    version: "stable"
    force: yes
    update: yes
- name: "create symlink to nvim config"
  ansible.builtin.file:
    src: "{{ git_dir }}/dotfiles/config/nvim"
    dest: "{{ home_dir }}/.config/nvim"
    state: link
    force: yes
